### ISSUE TITLE
Google translate looks weird and the buttons are messed up

### ISSUE THREAD

**Issue by dvdvideo1234** [lightswitch05/hosts#252] opened 2021-01-17 20:20 UTC
### Steps to reproduce
1. Install Pi-Hole ( Pi-hole v5.2.3 Web Interface v5.3 FTL v5.4 )
2. Install: https://github.com/lightswitch05/hosts/blob/master/docs/lists/ads-and-tracking-extended.txt
3. Open `https://translate.google.com/`
![image](https://user-images.githubusercontent.com/9112662/104854910-0b5f2400-5912-11eb-9588-3e73f0190d3c.png)

### Probable reasons 
Maybe some of these are needed for web functionality [`pihole -q`][ref-q]:
```txt
 Match found in https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt:
   google-translate-client.apponic.com
   translate.newrelic.com
   animetranslated.onesignal.com
   translate.googleusercontent.com.pathful.com
   translate.statcounter.com
   translategoogle.com
   www.translate.translategoogle.com
   ww.translategoogle.com
   ww1.translategoogle.com
   ww10.translategoogle.com
   www.translategoogle.com
   xnsx.translategoogle.com
   translate.whisk.com
   xn--oogletranslate-u5f.com
   translatej.forsurveys.hop.clickbank.net
   ww1.translate.alien-earth.org
```
### Reverting the list [`pihole -g`][ref-g]:
![image](https://user-images.githubusercontent.com/9112662/104855073-39913380-5913-11eb-8404-cf34b11ced25.png)
![image](https://user-images.githubusercontent.com/9112662/104855080-4dd53080-5913-11eb-935d-71fa87a28c39.png)

[ref-q]: https://docs.pi-hole.net/core/pihole-command/#query
[ref-g]: https://docs.pi-hole.net/core/pihole-command/#gravity

**Comment by lightswitch05** [comment] 2021-01-18 14:04
Duplicate of #249 - please see the solution there

**Closed by lightswitch05** 2021-01-18 14:04 UTC
Labels: broken-site, duplicate
