### ISSUE TITLE
[False positive] Fandom app not work

### ISSUE THREAD

**Issue by gluons** [lightswitch05/hosts#170] opened 2020-05-05 10:55 UTC
[FANDOM](https://play.google.com/store/apps/details?id=com.fandom.app) is broken when I use [**Ads & Tracking**](https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt) hosts.

Maybe because of https://github.com/lightswitch05/hosts/blob/6bf1212f8096e0e4072cf3634c816c4d2e0582c9/ads-and-tracking-extended.txt#L35799 ?

![Screenshot_2020-05-05-17-47-10-422_com fandom app](https://user-images.githubusercontent.com/4688092/81058516-ca94bb80-8ef8-11ea-84ba-2753be783ab6.jpg)

![Screenshot_2020-05-05-17-47-28-683_com adguard android](https://user-images.githubusercontent.com/4688092/81058743-3ecf5f00-8ef9-11ea-9c1d-8212b74aae8b.jpg)

**Comment by lightswitch05** [comment] 2020-05-05 12:21
Reproduced and temporally fixed by whitelisting `services.fandom.com`. I need to do some research before I decide if this is a false positive or not. Thanks for the report!

**Comment by lightswitch05** [comment] 2020-05-05 14:15
Added in https://github.com/lightswitch05/hosts/commit/cfdc7719

Looks like it could do some tracking on websites, but is of course breaking the app. I'll move it to the aggressive list

**Comment by lightswitch05** [comment] 2020-05-05 14:17
Moved, thanks for the report @gluons!

**Closed by lightswitch05** 2020-05-05 14:17 UTC
Labels: broken-site
