### ISSUE TITLE
GitHub zips

### ISSUE THREAD

**Issue by Stevieag** [lightswitch05/hosts#165] opened 2020-04-23 23:36 UTC
Match found in https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt: codeload.github.exacttarget.com

Today I began having issues downloading zips from GitHub. This was found as I use wget to pull a zip during an inline security check.
codeload.github.com was being blocked and so I have now whitelisted to allow through.

I at first thought it was GitHub at fault as they have had issues today but eventually I found this.

Not an issue to me but I felt it worth mentioning if unintentional or inconvenience to you or other use highlight it

**Comment by lightswitch05** [comment] 2020-04-23 23:40
Interesting, thanks for sharing @Stevieag! I have not blocked this host directly- but since I block all of exacttarget, it was automatically added.

I too use github zips, but I have not experienced any issues with it. Of course today, I had all sorts of issues with github since they had multiple outages.

Thanks again for sharing! Let’s keep it open and see if anyone else is having issues or not.

**Comment by XhmikosR** [comment] 2020-04-24 05:14
Seems to work fine here too. Any specific repo this happened? Do note they had an outage for quite some time.

**Comment by lightswitch05** [comment] 2020-04-29 15:01
any updates @Stevieag? I'm unable to reproduce.

**Comment by Stevieag** [comment] 2020-04-29 15:29
As I wrote, I added a whitelist entry. I will remove and try again.

**Comment by Stevieag** [comment] 2020-05-02 15:19
Hi, sorry for the delay.
i have today removed the entry from my white list and all is workin well.

I thoughroughly tested this at the time on numerous differing repos. At the time it was NOT possible to pull down a zip from any repo.
Adding the url allowed this to happen.

Some reason, today it now works fine.

**Comment by Stevieag** [comment] 2020-05-02 15:20
i guess this can be closed

**Comment by lightswitch05** [comment] 2020-05-04 17:17
Thank you for following up on this @Stevieag! Considering the github outage on that day and the inability for anyone to reproduce, I agree that’s it is safe to close this one.

**Closed** 2020-05-04 17:17 UTC
Labels: broken-site, invalid
