### ISSUE TITLE
[False Positive] tags.tiqcdn.com

### ISSUE THREAD

**Issue by FabioEight** [lightswitch05/hosts#269] opened 2021-03-31 18:19 UTC
Hello,

tags.tiqcdn.com is breaking this page: http://www.ricarica1click.vodafone.it/

http://www.ricarica1click.vodafone.it/ is used for recharge the mobile phone credit.
The issue is present using both browsers (Edge, Chrome on Windows, no adblock) and iPhone (website & app).
Whitelisting tags.tiqcdn.com fixes the issue.

**Comment by lightswitch05** [comment] 2021-04-23 12:43
This is a duplicate of #53 .

Scripts being blocked:

* `https://tags.tiqcdn.com/utag/vodafone/it-next/prod/utag.js`
* `https://tags.tiqcdn.com/utag/vodafone/it-next/prod/utag.sync.js`

Website is dying on `wa_gc(digitalData,"view");`. It looks like to me that this is a failure of the website to properly handle failure to load the tracking and not a case of the domain providing a needed service. Since this is a very common domain and isn't limited to this single website. I'm going to leave it blocked for now.

Thank you for the report!

**Closed by lightswitch05** 2021-04-23 12:43 UTC
