### ISSUE TITLE
infogram.com

### ISSUE THREAD

**Issue by crssi** [lightswitch05/hosts#207] opened 2020-07-28 06:25 UTC
Blockin e.infogram.com breaks statictic graphs... see for example: `https://www.24ur.com/novice/slovenija/podpora-vladi-janeza-janse-prvic-pod-40-odstotki.html`

Proposed sollution: Could you move `infogram.com` and `e.infogram.com` to aggressive list?

Additionaly, you have the following in the blocklist:
```
infogram.com
1577381777.infogram.com
601-ws.infogram.com
aacc.infogram.com
amchammexico.infogram.com
bokepcorona.infogram.com
bpd4ffp2mqarnriv7s8g.infogram.com
bqrcffp2mqao82s3c1gg.infogram.com
crm.infogram.com
detenganlavacuna.infogram.com
distancecalculator.infogram.com
e.infogram.com
getavirus-com.infogram.com
maskman626.infogram.com
middle-distance-classic.infogram.com
prezi.infogram.com
removeviruswithease.infogram.com
respirators.infogram.com
respiratory-care-sleep-medicine.infogram.com
s.infogram.com
status.infogram.com
torimaskepp.infogram.com
try.infogram.com
u002fe.infogram.com
vaccine.infogram.com
ws.infogram.com
www.infogram.com
ynet.infogram.com
```

Where having `infogram.com` doesn't make sense when using all other more specific subdomain.
It would make sense to have only `infogram.com` in aggressive and all the others without `infogram.com` in standard list.

Cheers and thank you for your hard work ❤️

**Comment by lightswitch05** [comment] 2020-07-28 11:40
Added by: https://github.com/lightswitch05/hosts/commit/68ec59804e86ff46ed9b5829088ecba64cff2485

> Added a bunch of malicious/hacked sites from https://www.joesandbox.com/analysis/345660

I think this whole domain might be a false positive. I'm on mobile at the moment, but once I get to a desktop I'll investigate the link and perhaps remove the entire domain from the list. Thanks for the report!

**Comment by lightswitch05** [comment] 2020-07-28 11:45
I don't want to provide the full URL since it was hosting malware, but I believe it's been removed from the website.

**Comment by lightswitch05** [comment] 2020-07-28 13:16
Thanks again for the report. I've removed everything except for `s.infogram.com` - which is obviously a tracker - and I've confirmed that the graphs load with it being blocked. I also added `ads.24ur.com` and `ads.api.24ur.si` from the URL you gave me.

**Comment by lightswitch05** [comment] 2020-07-28 13:18
fixed by https://github.com/lightswitch05/hosts/commit/1f685d3016aa5cd2ccf18c80824e91e53ec5bf73

**Closed by lightswitch05** 2020-07-28 13:18 UTC
Labels: false-positive

**Comment by crssi** [comment] 2020-07-28 13:22
`ads.api.24ur.si` should be removed... if blocked we have video breakages on this site.
Actually blocking only `ads.24ur.com` covers the ADS just fine.

Cheers

**Comment by lightswitch05** [comment] 2020-07-28 13:28
Oh, you are right. Ok, I've removed it - I cannot read the little message it says when its blocked, I thought it was just a video pre-roll message.

**Comment by crssi** [comment] 2020-07-28 13:31
Thank you, you are a gem. ♦️ ❤️

**Comment by lightswitch05** [comment] 2020-07-28 13:40
Haha thanks, it would be easier if I could read more languages then english. Removed by https://github.com/lightswitch05/hosts/commit/5ca905d39528b4ba234d9b30d67fb3e49cc64c20
